"""Fetch the product marks the "Built with" catalog renders.

The strip shows logos rather than names, which means the marks have to be real
ones rather than something drawn to look close. This pulls them from source and
writes a generated artifact, the same way the fixtures and the map geometry are
built — never hand-edited:

    python scripts/build_logos.py

Only the path geometry is kept, and the component fills it with `currentColor`, so
every mark renders monochrome in the palette. That is deliberate: fifteen
full-colour brand logos on a near-black instrument UI would be the loudest thing
on the page, and the strip is meant to be read, not to shout.

Sources and licensing:

  * **Simple Icons** (https://simpleicons.org) — CC0-1.0 for the icon files.
  * **DataHub** — the project's own mark from datahub-project/static-assets
    (Apache-2.0).

Trademarks remain with their owners. Using a mark to state what a project is
built with is nominative use, which is what this is.

Products with no usable vector mark are not faked. `uvicorn` publishes only a
raster, and NYC Open Data publishes none, so those are handled in the component —
Uvicorn is described inside FastAPI's entry, and NYC Open Data gets a typographic
tile rather than an invented symbol.
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "lib" / "logos.json"

SIMPLE_ICONS = "https://cdn.jsdelivr.net/npm/simple-icons@15/icons/{slug}.svg"
DATAHUB_MARK = (
    "https://raw.githubusercontent.com/datahub-project/static-assets/main"
    "/imgs/datahub-logo-color-mark.svg"
)

# key -> (source url, human name). The key is what the component looks up.
WANTED: dict[str, tuple[str, str]] = {
    "datahub": (DATAHUB_MARK, "DataHub"),
    "python": (SIMPLE_ICONS.format(slug="python"), "Python"),
    "fastapi": (SIMPLE_ICONS.format(slug="fastapi"), "FastAPI"),
    "pydantic": (SIMPLE_ICONS.format(slug="pydantic"), "Pydantic"),
    "pytest": (SIMPLE_ICONS.format(slug="pytest"), "pytest"),
    "nextjs": (SIMPLE_ICONS.format(slug="nextdotjs"), "Next.js"),
    "react": (SIMPLE_ICONS.format(slug="react"), "React"),
    "tailwind": (SIMPLE_ICONS.format(slug="tailwindcss"), "Tailwind CSS"),
    "typescript": (SIMPLE_ICONS.format(slug="typescript"), "TypeScript"),
    "cloudrun": (SIMPLE_ICONS.format(slug="googlecloud"), "Google Cloud Run"),
    "cloudflare": (SIMPLE_ICONS.format(slug="cloudflarepages"), "Cloudflare Pages"),
    "actions": (SIMPLE_ICONS.format(slug="githubactions"), "GitHub Actions"),
}

_VIEWBOX = re.compile(r'viewBox="([^"]+)"')
_PATH_D = re.compile(r'<path[^>]*\sd="([^"]+)"', re.S)


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "cauzon-build"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> None:
    marks: dict[str, dict[str, object]] = {}

    for key, (url, name) in WANTED.items():
        print(f"fetching {key:12} {url}")
        svg = fetch(url)

        viewbox = _VIEWBOX.search(svg)
        paths = _PATH_D.findall(svg)
        if not viewbox or not paths:
            raise SystemExit(f"{key}: could not parse a viewBox and path out of {url}")

        marks[key] = {
            "name": name,
            "viewBox": viewbox.group(1),
            # Every path, because a mark is not always one shape — DataHub's is
            # three. Fill comes from the component, not from the source file.
            "paths": paths,
            "source": url,
        }

    payload = {
        "note": (
            "Generated by scripts/build_logos.py. Marks from Simple Icons (CC0-1.0) "
            "and the DataHub project (Apache-2.0). Trademarks belong to their owners."
        ),
        "marks": marks,
    }
    OUT.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + "\n")

    size_kb = OUT.stat().st_size / 1024
    print(f"\nwrote {OUT.relative_to(ROOT)}")
    print(f"  marks {len(marks)}")
    print(f"  paths {sum(len(m['paths']) for m in marks.values())}")
    print(f"  size  {size_kb:.1f} KB")


if __name__ == "__main__":
    main()
