"""Regenerate the sample dossiers in examples/.

These are the artifacts Cauzon writes into DataHub, so they must be real agent
output — a judge should be able to evaluate output quality without running
anything. Re-run this after any change to the agent or the dossier format:

    PYTHONPATH=agent python scripts/build_examples.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "agent"))

from cauzon.agent import CauzonAgent  # noqa: E402
from cauzon.datahub_client import MockDataHubClient  # noqa: E402
from cauzon.models import Incident  # noqa: E402

# scenario -> output filename
TARGETS = {
    "freshness": "nyc-taxi-freshness-incident.md",
    "schema_change": "shop-schema-change-incident.md",
    "fanout": "app-join-fanout-incident.md",
}

_FIELDS = ["urn", "title", "description", "failed_assertion", "detected_at"]

_PREAMBLE = (
    "<!-- Generated by scripts/build_examples.py — real Cauzon output, not "
    "hand-written. Do not edit by hand. -->\n\n"
)


def main() -> None:
    out_dir = ROOT / "examples"
    for scenario, filename in TARGETS.items():
        client = MockDataHubClient(scenario=scenario)
        agent = CauzonAgent(client=client)
        raw = client.list_open_incidents()[0]
        incident = Incident(**{k: raw.get(k) for k in _FIELDS})
        diagnosis = agent.investigate(incident, write_back=True)

        dossier = CauzonAgent._render_dossier(diagnosis)
        (out_dir / filename).write_text(_PREAMBLE + dossier + "\n")
        print(
            f"  {filename:38} {diagnosis.root_cause.name:14} "
            f"{diagnosis.grounding.value}"
        )


if __name__ == "__main__":
    main()
