/**
 * Client-side replay of a real investigation.
 *
 * The hackathon rules reward a project URL a judge can open and test. The agent
 * is Python, so a static deploy would otherwise be a screenshot. This module
 * replays genuine agent output in the browser instead: `fixtures.json` is
 * generated by running the real `CauzonAgent` against the mock DataHub backend,
 * so the trace, the proof path, the rejected candidate and the write-backs are
 * all exactly what the agent produced — not prose written to look like it.
 *
 * It is a delivery mechanism, never a second source of truth. Regenerate with:
 *   PYTHONPATH=agent python scripts/build_fixtures.py
 */

import fixtures from "./fixtures.json";
import type { Diagnosis, Incident, TraceEvent } from "./types";

interface Fixture {
  incident: Incident;
  result: Diagnosis;
}

const SCENARIOS = fixtures as unknown as Record<string, Fixture>;

export const SCENARIO_ORDER = ["freshness", "schema_change", "fanout"] as const;
export type ScenarioKey = (typeof SCENARIO_ORDER)[number];

/** How long a phase's message lingers before the next one lands. */
const PHASE_DELAY_MS: Record<string, number> = {
  detect: 420,
  scope: 620,
  hypothesize: 760,
  prove: 900,
  writeback: 560,
};

export function mockIncidents(): Incident[] {
  return SCENARIO_ORDER.map((k) => SCENARIOS[k].incident);
}

export function scenarioForIncident(urn: string): ScenarioKey | null {
  return (
    SCENARIO_ORDER.find((k) => SCENARIOS[k].incident.urn === urn) ?? null
  );
}

export function diagnosisFor(urn: string): Diagnosis | null {
  const key = scenarioForIncident(urn);
  return key ? SCENARIOS[key].result : null;
}

/**
 * Replay one investigation, emitting each trace event on the cadence the real
 * agent produced them, then the finished diagnosis.
 *
 * Returns a cancel function so a component can abandon a run on unmount or when
 * the user starts a different investigation.
 */
export function replayInvestigation(
  urn: string,
  onEvent: (event: TraceEvent) => void,
  onDone: (diagnosis: Diagnosis) => void,
): () => void {
  const result = diagnosisFor(urn);
  if (!result) {
    onDone({} as Diagnosis);
    return () => {};
  }

  const events = result.trace ?? [];
  const timers: ReturnType<typeof setTimeout>[] = [];
  let elapsed = 260;

  events.forEach((event) => {
    timers.push(setTimeout(() => onEvent(event), elapsed));
    elapsed += PHASE_DELAY_MS[event.phase] ?? 600;
  });

  timers.push(setTimeout(() => onDone(result), elapsed + 240));

  return () => timers.forEach(clearTimeout);
}
